apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-receive-controller
  namespace: thanos
  labels:
    part-of: thanos
    app: thanos-receive-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: thanos-receive-controller
  namespace: thanos
  labels:
    part-of: thanos
    app: thanos-receive-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get
  - create
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thanos-receive-controller
  namespace: thanos
  labels:
    part-of: thanos
    app: thanos-receive-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: thanos-receive-controller
subjects:
- kind: ServiceAccount
  name: thanos-receive-controller
  namespace: thanos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-receive-controller
    part-of: thanos
  name: thanos-receive-controller
  namespace: thanos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-receive-controller
      part-of: thanos
  template:
    metadata:
      labels:
        app: thanos-receive-controller
        part-of: thanos
    spec:
      containers:
      - args:
        - --configmap-name=thanos-receive-base
        - --configmap-generated-name=thanos-receive-generated
        - --file-name=hashrings.json
        - --namespace=$(NAMESPACE)
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/observatorium/thanos-receive-controller:latest
        name: thanos-receive-controller
        ports:
        - containerPort: 8080
          name: http
      serviceAccount: thanos-receive-controller
